//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечное смещение.
        /// </summary>
        internal static string EndShift {
            get {
                return ResourceManager.GetString("EndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строить.
        /// </summary>
        internal static string HotkeyBuild {
            get {
                return ResourceManager.GetString("HotkeyBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить конечное смещение.
        /// </summary>
        internal static string HotkeyEndShiftMinus {
            get {
                return ResourceManager.GetString("HotkeyEndShiftMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить конечное смещение.
        /// </summary>
        internal static string HotkeyEndShiftPlus {
            get {
                return ResourceManager.GetString("HotkeyEndShiftPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить количество полос.
        /// </summary>
        internal static string HotkeyLinesMinus {
            get {
                return ResourceManager.GetString("HotkeyLinesMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить количество полос.
        /// </summary>
        internal static string HotkeyLinesPlus {
            get {
                return ResourceManager.GetString("HotkeyLinesPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строить параллельную.
        /// </summary>
        internal static string HotkeyParallel {
            get {
                return ResourceManager.GetString("HotkeyParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить радиус.
        /// </summary>
        internal static string HotkeyRadiusMinus {
            get {
                return ResourceManager.GetString("HotkeyRadiusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить радиус.
        /// </summary>
        internal static string HotkeyRadiusPlus {
            get {
                return ResourceManager.GetString("HotkeyRadiusPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Песочные часы.
        /// </summary>
        internal static string HotkeySandGlass {
            get {
                return ResourceManager.GetString("HotkeySandGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменшить сегмент.
        /// </summary>
        internal static string HotkeySegmentMinus {
            get {
                return ResourceManager.GetString("HotkeySegmentMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить сегмент.
        /// </summary>
        internal static string HotkeySegmentPlus {
            get {
                return ResourceManager.GetString("HotkeySegmentPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдвинуть  смещение к началу.
        /// </summary>
        internal static string HotkeyShiftBeginMinus {
            get {
                return ResourceManager.GetString("HotkeyShiftBeginMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдвинуть  смещение к концу.
        /// </summary>
        internal static string HotkeyShiftBeginPlus {
            get {
                return ResourceManager.GetString("HotkeyShiftBeginPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать смещение.
        /// </summary>
        internal static string HotkeyShowShift {
            get {
                return ResourceManager.GetString("HotkeyShowShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить начальное смещение.
        /// </summary>
        internal static string HotkeyStartShiftMinus {
            get {
                return ResourceManager.GetString("HotkeyStartShiftMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить начальное смещение.
        /// </summary>
        internal static string HotkeyStartShiftPlus {
            get {
                return ResourceManager.GetString("HotkeyStartShiftPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string InitError {
            get {
                return ResourceManager.GetString("InitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество полос.
        /// </summary>
        internal static string LineCount {
            get {
                return ResourceManager.GetString("LineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие настройки.
        /// </summary>
        internal static string OtherOption {
            get {
                return ResourceManager.GetString("OtherOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр.
        /// </summary>
        internal static string PreviewMode {
            get {
                return ResourceManager.GetString("PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегмент.
        /// </summary>
        internal static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбирите конечную точку.
        /// </summary>
        internal static string SelectEndInfo {
            get {
                return ResourceManager.GetString("SelectEndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбирите начальную точку.
        /// </summary>
        internal static string SelectStartInfo {
            get {
                return ResourceManager.GetString("SelectStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смещения.
        /// </summary>
        internal static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горячие клавиши.
        /// </summary>
        internal static string ShortCut {
            get {
                return ResourceManager.GetString("ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное смещение.
        /// </summary>
        internal static string StartShift {
            get {
                return ResourceManager.GetString("StartShift", resourceCulture);
            }
        }
    }
}
